version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: carrent
      POSTGRES_USER: car_admin
      POSTGRES_PASSWORD: SloZnyyP@ssw0rd!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: